# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_fos_user:
    resource: fos_user_routing.yml

_sonata_user:
    resource: sonata_user_routing.yml

_sonata_admin:
    resource: sonata_admin_routing.yml

_sonata_page:
    resource: sonata_page_routing.yml

#application_user:
#    resource: "@ApplicationUserBundle/Controller/"
#    type:     annotation

application_site:
    resource: "@ApplicationSiteBundle/Controller/"
    type:     annotation
    prefix:   /
