# Internal routing configuration to handle ESI
# ****** WARNING ******
# This route should be enabled with caution as it can open a security vulnerability
# see http://symfony.com/blog/security-release-symfony-2-0-20-and-2-1-5-released for more information
# ****** WARNING ******
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

_fos_user:
    resource: fos/fos_user_routing.yml

_sonata_user:
    resource: sonata/sonata_user_routing.yml

_sonata_admin:
    resource: sonata/sonata_admin_routing.yml

_sonata_page:
    resource: sonata/sonata_page_routing.yml

_sonata_media:
    resource: sonata/sonata_media_routing.yml

_sonata_news:
    resource: sonata/sonata_news_routing.yml

application_site:
    resource: "@ApplicationSiteBundle/Controller/"
    type:     annotation
    prefix:   /
