# sonata page bundle
sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
